### ISSUE TITLE
Add new Environment Ar2ProductionEnvironment

### ISSUE THREAD

**Issue by alessandroros** [DKE-Data/agrirouter-sdk-dotnet-standard#142]
Hi,
I would like to ask you if it has been already defined the new Ar2ProductionEnvironment in order to have it on the SDKs.
What I mean is that right now we have the class Ar2QualityAssuranceEnvironment which contains all values for the Quality environment but for next week we should have also the Production one.

Cheers,
Alessandro

**Comment by saschadoemer** [comment]
Hey,

no need for a new environment, since the URLs will be the same.

Regards

Sascha

**Comment by alessandroros** [comment]
Ok so the hostname for production will be https://*.qa.agrirouter.farm? How can we distinguish between Prod e Quality?

**Comment by saschadoemer** [comment]
No, the hosts remain the same as before the migration. Please see the docs, describing the necessary changes for production.

![image](https://github.com/user-attachments/assets/a2f7fc97-74a0-4097-98bf-133f291347af)

https://docs.agrirouter.com/agrirouter-interface-documentation/latest/ar2/testing.html

**Comment by alessandroros** [comment]
Thanks. Didn't know that.
