### ISSUE TITLE
RevokeService throws NullpointerException when calling Revoke for offboarded Endpoint

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-sdk-dotnet-standard#143]
**Describe the bug**
When calling Revoke for an endpoint that was already deleted in agrirouter, the RevokeService throws a nullpointer exception, as it cannot decode the result in:

OnboardErrorResponse onboardErrorResponse = JsonConvert.DeserializeObject<OnboardErrorResponse>(result.Content.ReadAsStringAsync().Result);

**To Reproduce**
1. Add an Endpoint in agrirouter using your API and store the relevant IDs
2. Delete the Endpoint in the agrirouter UI
3. Call the Revoke Service for that endpoint

**Expected behavior**
The API Call should be able to decode the errorResponse or - if not - throw a RevokeError informing that it was not able to deserialize the response. A nullpointer exception is too unclear.

**Comment by Frank-Wiebeler** [comment]
It seems to be an issue with the agrirouter itself.
https://github.com/DKE-Data/agrirouter/issues/43

I'll keep this one open anyway as it is not yet fixed and as a NullPointerException in such case is not a good solution

**Comment by oliverrahner** [comment]
Will be fixed in 3.9.1

**Comment by oliverrahner** [comment]
The underlying issue in agrirouter has just been fixed and deployed
