### ISSUE TITLE
Potential deadlocks

### ISSUE THREAD

**Issue by pvangilst-rovecom** [DKE-Data/agrirouter-sdk-dotnet-standard#60]
**Is your feature request related to a problem? Please describe.**
I'm noticing that the http calls are implemented using a synchronous strategy by calling `.Result` on a `Task<>`.
First of all, calling `Result` can lead to deadlocks in the entire application. So this library could be responsible for locking entire applications. (Not only the library calls itself).
Second, If you must, you should call `GetAwaiter().GetResult()` or you will either never see the exception that might occur, or the StackTrace is completely bogus. But I would **strongly** suggest to not do it. 😊

**Describe the solution you'd like**
Convert all methods to `Task<>` based operations and use `await` operations. If someone needs synchronized calls for whatever reason, they can call `GetAwaiter().GetResult()` themselves.
If you do not want to break existing applications just yet, you could mark the sync methods `Obsolete` and inside these methods call your new async methods with `GetAwaiter().GetResult()`. 😉

example:
```
public sealed class FetchMessageService
{
    [Obsolete]
    public List<MessageResponse> Fetch(OnboardResponse onboardResponse)
    {
        return this.FetchAsync(onboardResponse).GetAwaiter().GetResult();
    }

    public async Task<List<MessageResponse>> FetchAsync(OnboardResponse onboardResponse)
    {
        var data = await this.httpClient.GetStringAsync(uri);
        var list = Parse(data);
        return list;
    }
}
```

**Describe alternatives you've considered**
I'm afraid there are no alternatives.

**Additional context**
Stuff for reading: [Don't Block on Async Code](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by saschadoemer** [comment]
@pvangilst-rovecom there is a solution that might suit you within the linked PR.

#73
