### ISSUE TITLE
DELETE All messages does not work; comparable code in Java API works

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-sdk-dotnet-standard#83]
**Describe the bug**
Sending a request to delete all messages results in an ACK_with_failure; complaining about a missing list of messageIds.
A comparable code in the Java API - which also doesn't include a messageId-List - works fine.

**To Reproduce**
 1. Run this code in C# with one of your endpoints:
`var feedDeleteService = new FeedDeleteService(new HttpMessagingService(await GetAuthorizedHttpClient()));
            var ValidityPeriod = new ValidityPeriod()
            {
                SentFrom = UtcDataService.Timestamp(TimestampOffset.FourWeeks),
                SentTo = UtcDataService.NowAsTimestamp()

            };
        var feedDeleteParameters = new FeedDeleteParameters
            {
                ApplicationMessageId = MessageIdService.ApplicationMessageId(),
                OnboardResponse = await GetOnboardResponse(),
                ValidityPeriod = ValidityPeriod,
                TeamsetContextId = _teamSetContextId
            };

            await feedDeleteService.SendAsync(feedDeleteParameters);`
       Result will be an ACK_with_failure; Message is VAL_00017: "messageIds information required to process message is missing or malformed"
 2. Run this Delete-Command with one of your endpoints in Java:
`DeleteMessageService deleteMessageService = new DeleteMessageServiceImpl();
    DeleteMessageParameters deleteMessageParameters = new DeleteMessageParameters();
    deleteMessageParameters.setOnboardingResponse(onboardingResponse);
    deleteMessageParameters.setApplicationMessageId(UUID.randomUUID().toString());
    deleteMessageParameters.setSentFromInSeconds((long)0);
    deleteMessageParameters.setSentToInSeconds((long) Instant.now().getEpochSecond());
    deleteMessageService.send(deleteMessageParameters);`
 Result will be an ACK_With_Messages; listing all deleted MessageIDs

    
**Expected behavior**
Behaviour of C# API and Java API should match; C# should behave like Java

**Additional data**
Built command in C#: 
`bAokNDUyOTU4YWEtN2UwZi00OWZlLTk2NGQtYzA1NWM1MGNhNGQ0EAIaEGRrZTpmZWVkX2NvbmZpcm0iJGE5ZGJiMTIzLTA1MGYtNDJkOS05NWI5LTEyNDkyOGMxMzlmMUIKCMCX34cGEMCEPSkKJwolYWdyaXJvdXRlci5mZWVkLnJlcXVlc3QuTWVzc2FnZURlbGV0ZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`

Built Command in Java:
`RwokZTkyOGJmN2MtZTEzZS00YTM3LWI4ZjItMGUzMWJjYzFjNTllEAEaD2RrZTpmZWVkX2RlbGV0ZUIKCMmY34cGEMCEPUoAPwo9CiVhZ3Jpcm91dGVyLmZlZWQucmVxdWVzdC5NZXNzYWdlRGVsZXRlEhQaEgoEEMCEPRIKCL6Y34cGEMCEPQ==`

**Remark**
The messages as provided here are for different endpoints, however, the C#-Messages was already built for the Java-Endpoint as well and resulted in the error.

**Comment by Frank-Wiebeler** [comment]
One more comment: I also tried adding `MessageIds = new List<String>()` as well as  `MessageIds = new List<String>{}`; same with the SenderIds. This did not change the error.

When adding some random ID, I receive the error "MessageID not found", so it looks like there is at least a messagelist added when it's not empty.

**Comment by saschadoemer** [comment]
Fixed in the linked PR>
